# Site settings
title: Yet Another Useless Static Site
description: > # this means to ignore newlines until "baseurl:"
  TBA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
date_format: "%-d %B %Y"
permalink: pretty     # (default: date)

# author:
name:
email:
github_username: shoichiaizawa
twitter_username: shoichiaizawa

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: md,mkd,mkdn,mdown,mkdown,markdown
highlighter: rouge # (default: rouge, for Jekyll 3.0+)

# paginate: 5         # requires jekyll-paginate gem for Jekyll 3

exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md", "vendor"]
