# Site settings
title:
  en: Yet Another Useless Static Site
  jp: 巷でよくある静的サイト

description:
  en: Shoichi AIZAWA's personal website (under construction)
  jp: あいざわしょういちのウェブサイト（工事中）

index:
  en:
  jp: index-jp.html

basepath:
  en:
  jp: /jp/

feed:
  en: /feed.xml
  jp: /feed-jp.xml

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

date_format: "%-d %B %Y"
permalink: /:title     # (default: date)

# author:
name: Shoichi AIZAWA
email:
github_username: shoichiaizawa
twitter_username: shoichiaizawa

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'shoichiaizawa'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: md,mkd,mkdn,mdown,mkdown,markdown
highlighter: rouge # (default: rouge, for Jekyll 3.0+)

# paginate: 5         # requires jekyll-paginate gem for Jekyll 3

exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md", "vendor"]
